### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by isaa-ctaylor** [jgabriel98/spotifypiHome#8]
Hey there!

I wanted to look into using spotifypiHome in my home, using one rpi as both a server and client, and another rpi as a client. I ran `serverInstall.sh` and then `clientInstall.sh` on the server client, but the rpi doesn't show up on spotify or Bluetooth from my phone.

I was wondering what, if anything I am doing wrong?

Thanks

**Comment by jgabriel98** [comment]
Hello!
I have the same setup in my place.

Could you give more details about:
 - Wich Raspbian OS (name and version) are you using.
 - which device Bluetooth are you trying to connect? In other words, are
you trying to connect to the client node Bluetooth or the server node
Bluetooth?

**Comment by isaa-ctaylor** [comment]
I am running on rasbian 10, Buster. I am trying to connect to the server bluetooth.

**Comment by isaa-ctaylor** [comment]
I'm going to try flashing my rpi and starting with a fresh installation of the os, with nothing changed, and see if that works

**Comment by isaa-ctaylor** [comment]
I tried with a fresh Bullseye installation

I followed the following steps:

1. run `sudo apt install -y --no-install-recommends alsa-base alsa-utils bluez-tools`
2. run `wget https://github.com/jgabriel98/spotifypiHome/archive/refs/tags/v2.0.0.tar.gz && tar -xf v2.0.0.tar.gz spotifypiHome-2.0.0 && cd spotifypiHome-2.0.0 && sudo ./serverInstall.sh --no-shairport && sudo ./clientInstall.sh`

After this, it doesn't show up on spotify devices list, or Bluetooth devices on my phone.

Could you share how you installed, and if I did something wrong?


PS: I also noticed that it says that bluealsa was not found, and trying to run `bluealsa` from the command line, I get `bash: bluealsa: command not found`

I hope this is useful, thanks for your earlier speedy reply

**Comment by jgabriel98** [comment]
sorry for the wait. I was kinda busy.

yeah, it was vey usefull. There's two possibilities i can think of:
 1. I removed `bluealsa` from the dependencies and didn't check. So try to run `sudo apt install bluealsa` and do step 2. again.
 2. You're using raspbian 11 bullseye, and this OS doesn't have `bluealsa` anymore (see this [similar project readme](https://github.com/nicokaiser/rpi-audio-receiver) begin). For that you can
    - use a raspberry OS 10. But i can't guarantee spotify working, since raspotify updated to use raspberry OS 11 bullseye. From what i remember, i've only got some complains in the `raspotify.service` logs, but it seemed to be fine.
    - wait for me to get a workarround (probably i will use pipewire or pulseaudio to get bluetooth functionality). But this probably will take some time, since it would replace all the audiobackend. (Maybe a week to replace? idk)
    
    
Anyway, now i need to remind myself to update the readme about those OS conflicts.

**Comment by jgabriel98** [comment]
Update: Just found some examples to use pulseaudio for bluetooth input, i'm gona take a look this weekend, and hopefully get it back working.

**Comment by isaa-ctaylor** [comment]
I will have another go with buster later today

**Comment by isaa-ctaylor** [comment]
It's working!

I installed a fresh buster image, and it all works! 

I suggest adding bluealsa to the Bluetooth install packages in the readme, and maybe a note about connecting with Bluetooth using `bluetoothctl`

Thanks for the advice

**Comment by jgabriel98** [comment]
Good to know!

just a question, you couldn't connect with bluetooth without `bluetoohctl`? for what i remember i've fixed it (issue #3)

**Comment by isaa-ctaylor** [comment]
It may have just been my impatience, but it didn't seem to work just trying to pair without having to do anything with the pi. After pairing however, it connects just fine

**Comment by jgabriel98** [comment]
Thanks for letting me know

i'll take some time to do a fresh install and test the bluetooth (currently i'm on debian 11 bullseye, which doesn't have bluealsa anymore :/)
